CREATE DATABASE CHAMA;
USE CHAMA;
CREATE TABLE USERS_TABLE(
    USER_NAME VARCHAR(200),
    NATIONAL_ID INT NOT NULL,
    PHONE_NO INT,
    CLUSTER_NAME VARCHAR(200) NOT NULL,
    USER_STATUS VARCHAR(200),
    ACCOUNT_NO VARCHAR(200) NOT NULL,
    BANK_NAME VARCHAR(200) NOT NULL,
    AREA_OF_RESIDENCE VARCHAR(200),
    PRIMARY KEY(NATIONAL_ID),
    FOREIGN KEY(CLUSTER_NAME) REFERENCES CLUSTERS_TABLE(CLUSTER_NAME)
);

CREATE TABLE CLUSTERS_TABLE(
    CLUSTER_NAME VARCHAR(200) NOT NULL,
    NO_OF_MEMBERS INT,
    NO_PROJECTS INT,
    CLUSTER_LEADER VARCHAR(200),
    PROJECTS VARCHAR(200),
    PRIMARY KEY(CLUSTER_NAME)
);

CREATE TABLE PROJECTS_TABLE(
PROJECT_ID INT NOT NULL,
PROJECT_NAME VARCHAR(200),
PROJECT_LOCATION VARCHAR(200),
PROJECT_FUNDING DECIMAL(18,2),
PROJECT_DESCRIPTION TEXT,
PROGRESS_STATUS VARCHAR(200),
CLUSTER_NAME VARCHAR(200),
PRIMARY KEY(PROJECT_ID)
);
