CREATE DATABASE CHAMA;
USE CHAMA;
CREATE TABLE USERS_TABLE(
    USER_NAME VARCHAR(200),
    NATIONAL_ID INT NOT NULL,
    PHONE_NO INT,
    CLUSTER_NAME VARCHAR(200) REFERENCES CLUSTERS_TABLE(CLUSTER_NAME),
    USER_STATUS VARCHAR(200),
    ACCOUNT_NO VARCHAR(200) NOT NULL,
    BANK_NAME VARCHAR(200) NOT NULL,/
    AREA_OF_RESIDENCE VARCHAR(200),
    PRIMARY KEY(NATIONAL_ID)
    
);

CREATE TABLE CLUSTERS_TABLE(
    CLUSTER_NAME VARCHAR(200) NOT NULL,
    NO_OF_MEMBERS INT,
    NO_PROJECTS INT,
    CLUSTER_LEADER VARCHAR(200),
    PROJECTS VARCHAR(200),
    PRIMARY KEY(CLUSTER_NAME)
);

CREATE TABLE PROJECTS_TABLE(
PROJECT_ID INT NOT NULL,
PROJECT_NAME VARCHAR(200),
PROJECT_LOCATION VARCHAR(200),
PROJECT_FUNDING DECIMAL(18,2),
PROJECT_DESCRIPTION TEXT,
PROGRESS_STATUS VARCHAR(200),
CLUSTER_NAME VARCHAR(200) REFERENCES CLUSTERS_TABLE(CLUSTER_NAME),
PRIMARY KEY(PROJECT_ID)
);

SELECT * FROM USERS_TABLE;

SELECT  CLUSTER_LEADER, COUNT(NATIONAL_ID) AS NO_OF_MEMBERS, NO_PROJECTS,PROJECT_NAME,PROJECT_FUNDING,PROGRESS_STATUS
FROM clusters_table JOIN users_table 
ON clusters_table.CLUSTER_NAME = users_table.CLUSTER_NAME
JOIN projects_table 
ON clusters_table.CLUSTER_NAME = projects_table.CLUSTER_NAME

/*EQUI JOIN*/
Select CLUSTER_LEADER, PROJECT_NAME
 From CLUSTERS_TABLE, PROJECTS_TABLE 
 Where CLUSTERS_TABLE.CLUSTER_NAME = PROJECTS_TABLE.CLUSTER_NAME
  And PROGRESS_STATUS >= 5

SELECT * FROM USERS_TABLE;
SELECT USER_NAME,NATIONAL_ID, CLUSTER_NAME, PHONE_NO FROM USERS_TABLE Where USER_STATUS ="SECRETARY";
SELECT USER_NAME,NATIONAL_ID, CLUSTER_NAME, PHONE_NO FROM USERS_TABLE Where USER_STATUS ="CHAIRPERSON";
SELECT USER_NAME,NATIONAL_ID, CLUSTER_NAME, PHONE_NO FROM USERS_TABLE Where USER_STATUS ="TREASURER";
SELECT * FROM PROJECTS_TABLE;
SELECT * FROM PROJECTS_TABLE WHERE PROJECT_ID = 1;

SELECT CLUSTER_NAME, CLUSTER_LEADER, PROJECT_NAME, PROJECT_LOCATION, PROJECT_FUNDING, PROJECT_DESCRIPTION
FROM CLUSTERS_TABLE 
JOIN PROJECTS_TABLE ON
CLUSTERS_TABLE.CLUSTER_NAME = PROJECTS_TABLE.CLUSTER_NAME;


SELECT PROJECT_NAME, PROJECT_LOCATION, PROJECT_FUNDING, PROJECT_DESCRIPTION
WHERE CLUSTER_NAME = "A";

SELECT USER_NAME,NATIONAL_ID,PHONE_NO,USER_STATUS AREA_OF_RESIDENCE FROM USERS_TABLE WHERE CLUSTER_NAME = "A";

SELECT USER_NAME,NATIONAL_ID,PHONE_NO,USER_STATUS AREA_OF_RESIDENCE FROM USERS_TABLE WHERE USER_STATUS IS NOT NULL;

SELECT * FROM PROJECTS_TABLE WHERE PROJECT_FUNDING >= 500000;




